# Notice from https://www.usno.navy.mil/USNO (retrieved 2020-06-19):
#   The USNO websites aa.usno.navy.mil, ad.usno.navy.mil,
#   aristarchus.usno.navy.mil, maia.usno.navy.mil, rorf.usno.navy.mil,
#   and toshi.usno.navy.mil are undergoing modernization efforts.
#   The expected completion of the work and the estimated return of
#   service is Summer 2020.

url_to_tai_utc_dat='ftp://maia.usno.navy.mil/ser7/tai-utc.dat'
url_to_finals_data='ftp://maia.usno.navy.mil/ser7/finals.data'
